---
version: '3'
services:
  # Common settings for other services. You can inherit this by using:
  #   <<: *common
  x-common: &common
    image: docker.artifactory.autozone.com/release/store-operations/el7-build:2021.11.19
    working_dir: /workspace
    volumes:
      - "./:/workspace"

  build:
    <<: *common
    entrypoint:
      - /bin/bash
      - -c
      - |
        qmake-qt5 && make -j $$(nproc)

  check:
    <<: *common
    entrypoint:
      - /bin/bash
      - -c
      - |
        qmake-qt5 && \
        make -j $$(nproc) && \
        cd test && \
        qmake-qt5 && \
        make -j $$(nproc) && \
        ./test

  clean:
    <<: *common
    entrypoint:
      - /bin/bash
      - -c
      - |
        make distclean && \
        cd test && \
        make distclean

  client:
    <<: *common
    stdin_open: true
    tty: true
    entrypoint:
      - ./zbus-cli-ent.x

  shell:
    <<: *common
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
